spring:
  profiles:
    active: dev

logging:
  level:
    dev.temez.commander: DEBUG


test-plugin:
  localization:
    messages:
      commander:
        help:
          header-template: " <gray>- <white>Command usage for <yellow>%s"
          usage-template: " /%s %s- %s"
          subcommands-section: " <gray>- <white>Subcommands:"
        arguments:
          argument-must-be-float: "Argument must be float"
          argument-must-be-integer: "Argument must be integer"
          invalid-gamemode: "Invalid gamemode!"
          player-have-not-player-on-this-server: "This player didn't played on this server!"
          player-is-offline: "This player is offline"
          world-does-not-exists: "This world doesn't exists!"

        filter:
          command-source:
            available-only-from-console: "This command is available only from console"
            available-only-from-game: "This command is available only from game!"

      test-command-description: "This is a simple test command"
      test-subcommand-description: "This is a simple test subcommand"

      error-prefix: "<red>ERROR:<white> "
      bad-luck: "Better luck next time..."